### ISSUE TITLE
How to convert files from an url?

### ISSUE THREAD

**Issue by DanielGSoftware** [MaestroError/php-heic-to-jpg#12]
Hi @MaestroError, first I'd like to say thanks for the amazing package! We currently use a external service to convert our heic to jpg's, but it would be more beneficial to be able to do this directly :).

I'm trying to convert heic files from a amazon s3 url, but unfortunately this doesn't seem to work. I get `Couldn't convert HEIC to JPG: '' | Bin used: 'php-heic-to-jpg-darwin-amd64'`.

When I try to do it with an a [random heic file ](https://3.files.edl.io/b8f2/23/03/23/221649-2a340129-90bb-492f-a246-56ada339bbd4.heic) url I also get the same error. 

When using a local path to a file, it all works.

My question is, how do I convert a heic file from an url?

**Comment by DanielGSoftware** [comment]
This works: 
```php
file_put_contents(storage_path('test.heic'), file_get_contents($url));
$jpg = HeicToJpg::convertOnMac(storage_path('test.heic'));
```

I maybe should've asked the question slightly different: "Is it possible to convert files from an url?".
I'm thinking perhaps it's not the package's responsibility to do these previous steps.

**Comment by MaestroError** [comment]
Hi @DanielGSoftware 👍 Thanks for the feedback and sorry for late answer, I wanted to suggest the same file_put_contents function 😄 Yes, for now, converting from online is done by creating temp file and replacing it's content with new one before each convertation. I will add the "convertFromUrl" method in next releases 👍

**Comment by DanielGSoftware** [comment]
> Hi @DanielGSoftware 👍 Thanks for the feedback and sorry for late answer, I wanted to suggest the same file_put_contents function 😄 Yes, for now, converting from online is done by creating temp file and replacing it's content with new one before each convertation. I will add the "convertFromUrl" method in next releases 👍

Awesome! Thank you very much again for the work you're putting in 😃
