### ISSUE TITLE
Error : The file \"/Applications/MAMP/tmp/php/php7XIB7q\" cannot be opened:

### ISSUE THREAD

**Issue by harshadvala** [MaestroError/php-heic-to-jpg#19]
I getting errors on all methods 

`HeicToJpg::isHeic($filePath);`

`HeicToJpg::convertOnMac($filePath,"arm64")->saveAs($destPath);`

`HeicToJpg::convert($filePath,"arm64")->saveAs($destPath);`

**Comment by DanielGSoftware** [comment]
Seems like a file permission error maybe?

**Comment by MaestroError** [comment]
@harshadvala Yes, seems like a permission issue, but you have here some strange path `/Applications/MAMP/tmp/php/php7XIB7q`, what is it? All methods give you this error? Give more information about your device, environment and etc. please 👍

**Comment by harshadvala** [comment]
@MaestroError Thanks for the reply
I'm using a Macbook PRO M2 chip, all methods give the same error
Also I gave this permissions

`chmod -R 777 /Applications/MAMP/tmp/php/ `

![image](https://github.com/MaestroError/php-heic-to-jpg/assets/5895908/9f1dce6f-10f7-4c53-a8dd-704ddb9025b2)

**Comment by MaestroError** [comment]
@harshadvala Nice, but it has nothing to do with the tmp folder, can you share a full PHP script?

**Comment by MaestroError** [comment]
Hi, @harshadvala! Any updates from your side? Did you find the solution?

**Comment by MaestroError** [comment]
Wrapping this one up! New issues are always welcome. 👍
