### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by hooverweb** [MaestroError/php-heic-to-jpg#2]
I'm getting a PHP error while trying to convert. I'm running PHP 8.2 and GO 1.20.1:

`$tmp_img_file = Maestroerror\HeicToJpg::convert('/var/www/example.com/dev/image1.heic')->get();`

PHP Fatal error:  Uncaught Error: Call to a member function convertImage() on null in /home/user/vendor/maestroerror/php-heic-to-jpg/src/HeicToJpg.php:209

I've verified that the image path is correct. The same path fed into Imagick works (but fails due to lack of HEIC support), so I don't think it's a path issue.

**Comment by MaestroError** [comment]
Hi @hooverweb , thank you for the feedback! Just update it to version 0.3.1, should be fixed already 👍 Please, let me know if it will work well for you

**Comment by MaestroError** [comment]
You don't need a Go installed to make it work on your system, and PHP 7+ is supported too, was just a typo in the last update 😄

**Comment by hooverweb** [comment]
Thanks! I've updated to 0.3.1 and the error has changed to this:

`PHP Fatal error:  Uncaught RuntimeException: Couldn't convert HEIC to JPG:  in /home/user/vendor/maestroerror/php-heic-to-jpg/src/HeicToJpg.php:137`

**Comment by MaestroError** [comment]
@hooverweb Not sure about the reason, so I updated an error output to get more information. Please update it to version 0.3.2 and provide the error. One extra question, which OS do you use? It had problems with MacOS

**Comment by hooverweb** [comment]
I'm running Ubuntu 20.04. I've updated to 0.3.2. Here's the error:

`PHP Fatal error:  Uncaught RuntimeException: Couldn't convert HEIC to JPG: '' | Bin used: 'heicToJpg' HEIC: '/var/www/example.com/dev/image1.heic' Full Command: '/home/user/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg /var/www/example.com/dev/image1.heic /var/www/example.com/dev/image1.heic-133449335164025c9186c2b5.78592139' in /home/user/vendor/maestroerror/php-heic-to-jpg/src/HeicToJpg.php:139`

**Comment by MaestroError** [comment]
Thanks, @hooverweb! 🥳  I don't know why, but you have installed it in your `/home/user` directory, but it would be better if you install it in the root directory of your project, in this case: `/var/www/example.com/`. Here maybe we got some permission issue, so first, run this command in the console `/home/user/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg /var/www/example.com/dev/image1.heic /var/www/example.com/dev/image1.heic-133556335164025c9186c2b5.78592139` and show me the output 👍

**Comment by hooverweb** [comment]
That seems to have worked! I'll move the install. Thanks for your help!

```
JPG: --/var/www/example.com/dev/image1.heic-133556335164025c9186c2b5.78592139--
Created by MaestroError
```

**Comment by MaestroError** [comment]
Nice 🥳 Thank you @hooverweb for the feedback! Thanks to you I updated the documentation with a note to install the package in the root directory. Feel free to get in touch if need any help from me 👍
