### ISSUE TITLE
Couldn't convert HEIC to JPG

### ISSUE THREAD

**Issue by WebdevJakHQ** [MaestroError/php-heic-to-jpg#20]
Hi I'm getting an error message 'Couldn't convert HEIC to JPG'. It's working fine on my local enviroment but when I upload this on my test link its now giving me that error message.

I've looked into the file and I found that on line 129 
`exec($command, $output)` 
This is not returning anything. Whereas on my local enviroment it is. Any suggestions on how to fix this?

**Comment by DanielGSoftware** [comment]
What is the OS/arch of your local and "test" environment?

**Comment by MaestroError** [comment]
Hi @WebdevJakHQ! Please answer the @DanielGSoftware and also provide the full error (There should be a command)
