### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by mattdabell** [MaestroError/php-heic-to-jpg#21]
Hi there,

Many thanks for this package. I am trying to install 1.0 but composer doesn't seem to like it:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires maestroerror/php-heic-to-jpg 1.0 -> satisfiable by maestroerror/php-heic-to-jpg[v1.0].
    - maestroerror/php-heic-to-jpg v1.0 requires maestroerror/heif-converter dev-maestro -> found maestroerror/heif-converter[dev-maestro] but it does not match your minimum-stability.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

is there anything I am doing wrong here?

Thanks,
Matt

**Comment by mattdabell** [comment]
I resolve by adding this to composer.json:
```
"minimum-stability": "dev",
```

**Comment by MaestroError** [comment]
Hello, @mattdabell! Thanks for reaching out 👍 Happy to hear you resolved the issue. As it seems we had required "heif-converter" dev-maestro now I require version 0.1, so you will not face the same issue in future 👍
