### ISSUE TITLE
the exec error

### ISSUE THREAD

**Issue by a3mqq** [MaestroError/php-heic-to-jpg#23]
`Call to undefined function Maestroerror\exec()`

when i upload the project on linux shared host

**Comment by MaestroError** [comment]
Hi @a3mqq, thanks for the feedback! Are you using Composer on your Linux shared host for your project?

**Comment by a3mqq** [comment]
Yes, when I upload it to shared linux hosting, it does not work well, but it works fine in local
Thanks for the response

**Comment by radekmichlik** [comment]
The `exec` function is probably disabled on your shared hosting. You would need to enable it in php.ini or move to different location where it is enabled.

**Comment by MaestroError** [comment]
Thanks @radekmichlik! 🙏  Yes, @a3mqq you should ask your providers to make it available for you, or try to move on different type of hosting or different company which ensures more control over cPanel 👍

**Comment by MaestroError** [comment]
Thank you all for your contributions and insights on this issue. At this point, we believe it's resolved and will be closing it. However, if you encounter any related problems or have further suggestions, please don't hesitate to open a new issue. 🌟
