### ISSUE TITLE
Debian x86_64: segmentation violation with heicToJpg, "cannot execute binary" with php-heic-to-jpg-linux-arm64

### ISSUE THREAD

**Issue by michapietsch-streamline** [MaestroError/php-heic-to-jpg#27]
Hey,

on our Debian x86_64 with v1.0.4 I can't seem to find any working executable.

I'm running the full command in the terminal, replacing the binaries.

<details>
<summary>With php-heic-to-jpg-linux-arm64 I get:</summary>
vendor/maestroerror/php-heic-to-jpg/src/../bin/php-heic-to-jpg-linux-arm64 "storage/app/temp-files/20230914/6471f2e5-b306-49b3-b32c-8f9420d6dfed" "storage/app/temp-files/20230914/6471f2e5-b306-49b3-b32c-8f9420d6dfed-4749348066502c807d434b9.15606759" 2>&1

-bash: vendor/maestroerror/php-heic-to-jpg/src/../bin/php-heic-to-jpg-linux-arm64: cannot execute binary file: Exec format error
</details>

<details>
<summary>With heicToJpg I get:</summary>
vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg "storage/app/temp-files/20230914/6471f2e5-b306-49b3-b32c-8f9420d6dfed" "storage/app/temp-files/20230914/6471f2e5-b306-49b3-b32c-8f9420d6dfed-4749348066502c807d434b9.15606759" 2>&1

2023/09/14 11:02:16 heif: no EXIF found
unexpected fault address 0x7fc434021010
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fc434021010 pc=0x4aeffc]

goroutine 1 [running]:
runtime.throw({0x530360?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000191308 sp=0xc0001912d8 pc=0x4465fd
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:851 +0x28a fp=0xc000191368 sp=0xc000191308 pc=0x45ab6a
image/jpeg.yCbCrToYCbCr(0xc0000fc100, {0x5eb8e0?, 0x0?}, 0xc000191470, 0xc000191970, 0xc000191570)
	/usr/local/go/src/image/jpeg/writer.go:461 +0x17c fp=0xc0001913e8 sp=0xc000191368 pc=0x4aeffc
image/jpeg.(*encoder).writeSOS(0xc0000000c0, {0x552a78?, 0xc0000fc100?})
	/usr/local/go/src/image/jpeg/writer.go:547 +0x485 fp=0xc000191da0 sp=0xc0001913e8 pc=0x4af665
image/jpeg.Encode({0x552758?, 0xc000013188?}, {0x552a78, 0xc0000fc100}, 0x0)
	/usr/local/go/src/image/jpeg/writer.go:634 +0x33f fp=0xc000191e18 sp=0xc000191da0 pc=0x4afadf
main.convertHeicToJpg({0x7ffd8b31965b?, 0xc00009e718?}, {0x7ffd8b3196a8, 0x6d})
	/go/src/github.com/MaestroError/php-heic-to-jpg/main.go:69 +0x1a6 fp=0xc000191ed8 sp=0xc000191e18 pc=0x4c0906
main.main()
	/go/src/github.com/MaestroError/php-heic-to-jpg/main.go:22 +0x50 fp=0xc000191f80 sp=0xc000191ed8 pc=0x4c0570
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000191fe0 sp=0xc000191f80 pc=0x448ee7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000191fe8 sp=0xc000191fe0 pc=0x473801

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00009efb0 sp=0xc00009ef90 pc=0x449316
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc00009efe0 sp=0xc00009efb0 pc=0x449150
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00009efe8 sp=0xc00009efe0 pc=0x473801
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00009f780 sp=0xc00009f760 pc=0x449316
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00009f7c8 sp=0xc00009f780 pc=0x435f6e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00009f7e0 sp=0xc00009f7c8 pc=0x42b446
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00009f7e8 sp=0xc00009f7e0 pc=0x473801
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000c8000?, 0x551008?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00009ff70 sp=0xc00009ff50 pc=0x449316
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x5fc920)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00009ffa0 sp=0xc00009ff70 pc=0x433eb3
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc00009ffc8 sp=0xc00009ffa0 pc=0x434485
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00009ffe0 sp=0xc00009ffc8 pc=0x42b3e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00009ffe8 sp=0xc00009ffe0 pc=0x473801
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x5fcd60?, 0x60?, 0x78?, 0xc00009e770?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00009e628 sp=0xc00009e608 pc=0x449316
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00009e7e0 sp=0xc00009e628 pc=0x42a487
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00009e7e8 sp=0xc00009e7e0 pc=0x473801
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x45
</details>

Here's the `file` information:
```
file heicToJpg

heicToJpg: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=149f9c872787030f9f4eea4de7d9f255736cd371, for GNU/Linux 3.2.0, with debug_info, not stripped

file php-heic-to-jpg-linux-arm64

php-heic-to-jpg-linux-arm64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, Go BuildID=congiia-9eihUneMMSRM/0u1XgVabdwW4_DOqiRug/Bp_fdBq7zZjzqbukpHkj/ZDYppgUmdVCCQx1EnmYL, BuildID[sha1]=25bffd2c852fa88dc005587adef3249d43907197, not stripped
```

`uname -r`:
```
5.10.0-25-amd64
```

**Comment by MaestroError** [comment]
Hi @michapietsch-streamline! Thanks for your feedback! Your correct bin file is `heicToJpg` but it throws an error, which is completely unclear right now for me. We had a similar issue because of the old version of the OS, maybe upgrading your Debian x86_64 to the new version would help 👍 Please, try it and feel free to reach out in any case ❤️

**Comment by GasparM** [comment]
Hi, I have the exact same issue as @michapietsch-streamline. I'm running Ubuntu 22.04 x86_64. I got the same two issues while running full command on my terminal. Is there a solution ? @michapietsch-streamline have you found a workaound ? Thanks for your time

**Comment by michapietsch-streamline** [comment]
@GasparM no, unfortunately not.

**Comment by MaestroError** [comment]
I think the same issue is discussed here: https://github.com/MaestroError/php-heic-to-jpg/issues/30

If you have some time @michapietsch-streamline, can you confirm that the second (EXIF not found) error was only with some images but for some images it worked well? 

Or, do you tested it on different images from different sources? And, did you try with an image created by iPhone?

**Comment by MaestroError** [comment]
Please check out this issue and comment https://github.com/MaestroError/php-heic-to-jpg/issues/25#issuecomment-1903865682
