### ISSUE TITLE
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21'

### ISSUE THREAD

**Issue by banchap** [MaestroError/php-heic-to-jpg#29]
I'm trying to run HeicToJpg::convert() on Centos7 server i receive error. 
``Couldn't convert HEIC to JPG: '(my path)/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by (my path)/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg)' | Bin used: 'heicToJpg' HEIC: '(path to image)/file_11.heic' Full Command: '(my path)/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg "(path to image)/file_11.heic" "(path to image)/file_11.heic-1291524540650db72df3bf14.54402199" 2>&1' Output from heif-converter-image exe:``   

I've tried to launch bin heicToJpg from console and received the same error 

`./heicToJpg: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by ./heicToJpg)`

should I install something additional?

**Comment by LukeJennings1** [comment]
Same issue here with installing to plesk....any help?

**Comment by MaestroError** [comment]
We had issues with CentOS before. I am sorry, but it is hard to maintain on all distributions of Linux. So we decided to stick to Ubuntu latest using GitHub actions.

Check this out:

> It's not "missing", it is just newer than the glibc packages that ship as part of CentOS 7 and that will never change. That version was decided when 7.0 was released and will not change for the entire 10 year lifecycle of CentOS 7. To change it would require every single thing that is part of CentOS 7 to be rebuilt and that is not going to happen.
> 
> The problem is not CentOS, it is that the application you are using is built using a newer glibc than ships with CentOS 7. We cannot control what a developer uses to build things but if they build against a newer glibc than we ship then it will not work. It's their problem to build against the right version not ours to supply the newer version that would break everything else.
> 
> Also, your CentOS 7.7 is *way* out of date and needs updating. It won't fix this problem but it will patch all the things that have been updated in the last 2 and a half years since 7.7 came out. The current (and last) version of CentOS 7 is 7.9.

https://forums.centos.org/viewtopic.php?t=78832
