### ISSUE TITLE
Laravel _ segmentation violation: Couldn't convert HEIC to JPG

### ISSUE THREAD

**Issue by lily2908** [MaestroError/php-heic-to-jpg#30]
I am getting this error on some images but some images work on my local.   I am using the correct convert vs. HeicToJpg::convert methods.

Getting this error:

`RuntimeException: Couldn't convert HEIC to JPG: '2023/09/28 09:42:58 heif: no EXIF found\nunexpected fault address 0x7f7969303010\nfatal error: fault\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f7969303010 pc=0x4aeffc]\n\ngoroutine 1 [running]:\nruntime.throw({0x530360?, 0x0?})\n	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000129308 sp=0xc0001292d8 pc=0x4465fd\nruntime.sigpanic()\n	/usr/local/go/src/runtime/signal_unix.go:851 +0x28a fp=0xc000129368 sp=0xc000129308 pc=0x45ab6a\nimage/jpeg.yCbCrToYCbCr(0xc00008e080, {0x5eb8e0?, 0x0?}, 0xc000051470, 0xc000051970, 0xc000051570)\n	/usr/local/go/src/image/jpeg/writer.go:461 +0x17c fp=0xc0001293e8 sp=0xc000129368 pc=0x4aeffc\nimage/jpeg.(*encoder).writeSOS(0xc000140000, {0x552a78?, 0xc00008e080?})\n	/usr/local/go/src/image/jpeg/writer.go:547 +0x485 fp=0xc000129da0 sp=0xc0001293e8 pc=0x4af665\nimage/jpeg.Encode({0x552758?, 0xc0000120a8?}, {0x552a78, 0xc00008e080}, 0x0)\n	/usr/local/go/src/image/jpeg/writer.go:634 +0x33f fp=0xc000129e18 sp=0xc000129da0 pc=0x4afadf\nmain.convertHeicToJpg({0x7fff8491c341?, 0xc000040718?}, {0x7fff8491c3a1, 0x81})\n	/go/src/github.com/MaestroError/php-heic-to-jpg/main.go:69 +0x1a6 fp=0xc000129ed8 sp=0xc000129e18 pc=0x4c0906\nmain.main()\n	/go/src/github.com/MaestroError/php-heic-to-jpg/main.go:22 +0x50 fp=0xc000129f80 sp=0xc000129ed8 pc=0x4c0570\nruntime.main()\n	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000129fe0 sp=0xc000129f80 pc=0x448ee7\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000129fe8 sp=0xc000129fe0 pc=0x473801\n\ngoroutine 2 [force gc (idle)]:\nruntime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040fb0 sp=0xc000040f90 pc=0x449316\nruntime.goparkunlock(...)\n	/usr/local/go/src/runtime/proc.go:387\nruntime.forcegchelper()\n	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000040fe0 sp=0xc000040fb0 pc=0x449150\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x473801\ncreated by runtime.init.6\n	/usr/local/go/src/runtime/proc.go:293 +0x25\n\ngoroutine 3 [GC sweep wait]:\nruntime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000041780 sp=0xc000041760 pc=0x449316\nruntime.goparkunlock(...)\n	/usr/local/go/src/runtime/proc.go:387\nruntime.bgsweep(0x0?)\n	/usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000417c8 sp=0xc000041780 pc=0x435fbe\nruntime.gcenable.func1()\n	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000417e0 sp=0xc0000417c8 pc=0x42b446\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000417e8 sp=0xc0000417e0 pc=0x473801\ncreated by runtime.gcenable\n	/usr/local/go/src/runtime/mgc.go:178 +0x6b\n\ngoroutine 4 [GC scavenge wait]:\nruntime.gopark(0xc00001e070?, 0x551008?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000041f70 sp=0xc000041f50 pc=0x449316\nruntime.goparkunlock(...)\n	/usr/local/go/src/runtime/proc.go:387\nruntime.(*scavengerState).park(0x5fc920)\n	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000041fa0 sp=0xc000041f70 pc=0x433eb3\nruntime.bgscavenge(0x0?)\n	/usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000041fc8 sp=0xc000041fa0 pc=0x4344a5\nruntime.gcenable.func2()\n	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000041fe0 sp=0xc000041fc8 pc=0x42b3e6\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x473801\ncreated by runtime.gcenable\n	/usr/local/go/src/runtime/mgc.go:179 +0xaa\n\ngoroutine 5 [finalizer wait]:\nruntime.gopark(0x1a0?, 0x5fcd60?, 0x60?, 0x78?, 0xc000040770?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040628 sp=0xc000040608 pc=0x449316\nruntime.runfinq()\n	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000407e0 sp=0xc000040628 pc=0x42a487\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x473801\ncreated by runtime.createfing\n	/usr/local/go/src/runtime/mfinal.go:163 +0x45\n\ngoroutine 6 [GC worker (idle)]:\nruntime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000042750 sp=0xc000042730 pc=0x449316\nruntime.gcBgMarkWorker()\n	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000427e0 sp=0xc000042750 pc=0x42cfb1\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x473801\ncreated by runtime.gcBgMarkStartWorkers\n	/usr/local/go/src/runtime/mgc.go:1199 +0x25\n\ngoroutine 18 [GC worker (idle)]:\nruntime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003c750 sp=0xc00003c730 pc=0x449316\nruntime.gcBgMarkWorker()\n	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00003c7e0 sp=0xc00003c750 pc=0x42cfb1\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x473801\ncreated by runtime.gcBgMarkStartWorkers\n	/usr/local/go/src/runtime/mgc.go:1199 +0x25\n\ngoroutine 19 [GC worker (idle)]:\nruntime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003cf50 sp=0xc00003cf30 pc=0x449316\nruntime.gcBgMarkWorker()\n	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00003cfe0 sp=0xc00003cf50 pc=0x42cfb1\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003cfe8 sp=0xc00003cfe0 pc=0x473801\ncreated by runtime.gcBgMarkStartWorkers\n	/usr/local/go/src/runtime/mgc.go:1199 +0x25\n\ngoroutine 34 [GC worker (idle)]:\nruntime.gopark(0xf6ee0b57ccf5?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000696750 sp=0xc000696730 pc=0x449316\nruntime.gcBgMarkWorker()\n	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0006967e0 sp=0xc000696750 pc=0x42cfb1\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0006967e8 sp=0xc0006967e0 pc=0x473801\ncreated by runtime.gcBgMarkStartWorkers\n	/usr/local/go/src/runtime/mgc.go:1199 +0x25\n\ngoroutine 35 [GC worker (idle)]:\nruntime.gopark(0xf6ee0b54ca2b?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000696f50 sp=0xc000696f30 pc=0x449316\nruntime.gcBgMarkWorker()\n	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000696fe0 sp=0xc000696f50 pc=0x42cfb1\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000696fe8 sp=0xc000696fe0 pc=0x473801\ncreated by runtime.gcBgMarkStartWorkers\n	/usr/local/go/src/runtime/mgc.go:1199 +0x25\n\ngoroutine 20 [GC worker (idle)]:\nruntime.gopark(0xf6ee0b54cade?, 0x0?, 0x0?, 0x0?, 0x0?)\n	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00003d750 sp=0xc00003d730 pc=0x449316\nruntime.gcBgMarkWorker()\n	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00003d7e0 sp=0xc00003d750 pc=0x42cfb1\nruntime.goexit()\n	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003d7e8 sp=0xc00003d7e0 pc=0x473801\ncreated by runtime.gcBgMarkStartWorkers\n	/usr/local/go/src/runtime/mgc.go:1199 +0x25' | Bin used: 'heicToJpg' HEIC: '/var/www/html/storage/app/public/socialwall_posts/iUJKFJtZ09kNSOzZypO9nQT0I9kCLDEomGRLb7iX.heic' Full Command: '/var/www/html/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg &quot;/var/www/html/storage/app/public/socialwall_posts/iUJKFJtZ09kNSOzZypO9nQT0I9kCLDEomGRLb7iX.heic&quot; &quot;/var/www/html/storage/app/public/socialwall_posts/iUJKFJtZ09kNSOzZypO9nQT0I9kCLDEomGRLb7iX.heic-149581381565154aa2b7a901.54543954&quot; 2&gt;&amp;1' Output from heif-converter-image exe:  in file /var/www/html/vendor/maestroerror/php-heic-to-jpg/src/HeicToJpg.php on line 204`

**Comment by Mbahmo** [comment]
@lily2908, did you finally manage to fix your problem? I faced the same issue today when I attempted to implement HeicToJpg as well.

**Comment by kTOTk** [comment]
A similar problem, tested with files from the network, also created in the editor. I haven't checked with iphone photos. The heic file that is in the project is converted without errors

**Comment by MaestroError** [comment]
Please check out this issue and comment https://github.com/MaestroError/php-heic-to-jpg/issues/25#issuecomment-1903865682
