### ISSUE TITLE
Compiled binaries are not compatible with Cent OS 7

### ISSUE THREAD

**Issue by Muazzamkhan95** [MaestroError/php-heic-to-jpg#41]
Compiled binaries are not compatible with Cent OS 7 becauase its using GLIB glibc-2.17-326.el7_9.x86_64 and these binaries are compiled with GLIBCXX_3.4.21.
can you please suggest how can i handle that as my server i am unable to upgrade OS due to it will not support cpanel. i have vps

 "message": "Couldn't convert HEIC to JPG: '/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg)' | Bin used: 'heicToJpg' HEIC: public/storage/PLTSWZNCzNuZmJ.heic' Full Command: '/vendor/maestroerror/php-heic-to-jpg/src/../bin/heicToJpg \"/public/storage/PLTSWZNCzNuZmJ.heic\" \"/public/storage/PLTSWZNCzNuZmJ.heic-17096726566600e542cc83d9.54541371\" 2>&1' Output from heif-converter-image exe: ",
    "exception": "RuntimeException",

**Comment by MaestroError** [comment]
Hello @Muazzamkhan95! Thanks for reaching out 👍 Unfortunately one of the package users tried to install this library on Cent OS but he couldn't. I guess, it is nearly impossible, so we don't support Cent OS 😞

If you can't switch it to Ubuntu, the only thing I can do is recommend other solutions:

- [heif-converter-image](https://github.com/MaestroError/heif-converter-image) (read the documentation)
- iMagick extension with [Intervention/image](https://github.com/Intervention/image) package
- JS: [heic2any](https://github.com/alexcorvi/heic2any)

**Comment by Muazzamkhan95** [comment]
Thanks for the suggestions and its a really nice package. looking forward for the updates.

**Comment by MaestroError** [comment]
Thank you @Muazzamkhan95 ❤️
