### ISSUE TITLE
Couldn't convert HEIC to JPG /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by davide1995** [MaestroError/php-heic-to-jpg#44]
Thank you very much for this library. Locally (with macOS) everything works correctly but as soon as I deploy in production it seems that a third-part library is missing despite the fact that your README specifies that `It uses binary file created with Go language and has no dependencies on any other PHP libraries, extensions or third-part software`.

The machine in production is (according `uname -a`):
`Linux h2web270 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1+deb9u1~deb8u1 (2020-06-09) x86_64 GNU/Linux`

Error encountered during covnersion:
`HP Fatal error:  Uncaught RuntimeException: Couldn't convert HEIC to JPG: '/home/clients/12/sites/test/bin/heicToJpg: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found`

Unfortunately, I cannot install any add-ons on the prod machine as it is an unmanaged web hosting and I do not have admin permissions to install the missing library.

Command `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` gives me following output back:
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

How can I make it work in production?

Thanks

**Comment by MaestroError** [comment]
Hello @davide1995! Thanks for reaching out! 👍 You are right, it has no other dependencies but unfortunately it needs that library from the OS side 😕

Generally we hoped that all OS has it by default (it is true for modern OS) but we already found out that Centos doesn't support it. I guess there is the same problem in your case, check this issue #41

**Comment by davide1995** [comment]
It's a shame it cannot be solved by just recompiling the binary with e.g. GLIBCXX_3.4.20 which is supported by my machine 😕.
Anyway, I solved it by using the JS library [heic2any](https://www.npmjs.com/package/heic2any) directly in my client.
Thanks for the suggested issue

**Comment by MaestroError** [comment]
@davide1995 Happy to help 👍
